export default [
  'aeroporto',
  'aliados',
  'alto de pega',
  'araujo',
  'arvore',
  'azurara',
  'baguim',
  'bolhao',
  'botica',
  'brito capelo',
  'camara gaia',
  'camara matosinhos',
  'campainha',
  'campanha',
  'campo 24 agosto',
  'candido dos reis',
  'carreira',
  'carolina michaelis',
  'casa da musica',
  'castelo da maia',
  'combatentes',
  'contumil',
  'crestins',
  'custio',
  'custoias',
  'd. joao ii',
  'espaco natureza',
  'esposade',
  'estadio do dragao',
  'estadio do mar',
  'fanzeres',
  'faria guimaraes',
  'fonte do cuco',
  'forum maia',
  'francos',
  'galiza',
  'general torres',
  'heroismo',
  'hospital santo antonio',
  'hospital sao joao',
  'hospital santos silva',
  'i.p.o.',
  'ismai',
  'jardim do morro',
  'joao de deus',
  'lapa',
  'levada',
  'lidador',
  'mandim',
  'manuel leao',
  'marques',
  'matosinhos sul',
  'mercado',
  'mindelo',
  'modivas centro',
  'modivas sul',
  'nasoni',
  'nau vitoria',
  'parque maia',
  'parque real',
  'pedras rubras',
  'pedro hispano',
  'pias',
  'polo universitario',
  'portas fronhas',
  'povoa de varzim',
  'ramalde',
  'rio tinto',
  'salgueiros',
  'santa clara',
  'santo ovidio',
  'sao bento',
  'sao bras',
  'senhor de matosinhos',
  'senhora da hora',
  'sete bicas',
  'trindade',
  'varziela',
  'vasco da gama',
  'vc fashion outlet/modivas',
  'venda nova',
  'verdes',
  'vila d’este',
  'via rapida/viso',
  'vila do conde',
  'vilar do pinheiro',
  'zona industrial',
]
